VirtualDeckWeb/Models/TokenPackViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace VirtualDeckWeb.Models
{
    public class TokenPackViewModel
    {
        [ScaffoldColumn(false)]
        public int Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int Tokens { get; set; }

        [Required(ErrorMessage = "Debes introducir el número de la tarjeta de crédito")]
        [Display(Name = "Número de la tarjeta")]
        //[Display(Prompt = "Nombre del artículo", Description = "Nombre del artículo", Name = "Nombre ")]
        public string CardNumber { get; set; }
        [Required(ErrorMessage = "Debes introducir la fecha de caducidad de la tarjeta")]
        [Display(Name = "Fecha de caducidad")]
        [DataType(DataType.Date)]
        [RegularExpression(@"^([0-2][0-9]|(3)[0-1])(/)(((0)[0-9])|((1)[0-2]))(/)\d{4}$", ErrorMessage = "El formato de la fecha debe ser DD/MM/YYYY")]
        public Nullable<DateTime> ExpiryDate { get; set; }
        [Required(ErrorMessage = "Debes introducir el CVV")]
        [Display(Name = "CVV")]
        public string CVV { get; set; }
        [Required(ErrorMessage = "Debes introducir el nombre del titular de la tarjeta")]
        [Display(Name = "Titular de la tarjeta")]
        public string AccountHolder { get; set; }
    }
}

VirtualDeckWeb/Controllers/TokenPackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VirtualDeckGenNHibernate.CAD.VirtualDeck;
using VirtualDeckGenNHibernate.CEN.VirtualDeck;
using VirtualDeckGenNHibernate.CP.VirtualDeck;
using VirtualDeckGenNHibernate.EN.VirtualDeck;
using VirtualDeckWeb.Assemblers;
using VirtualDeckWeb.Models;

namespace VirtualDeckWeb.Controllers
{
    public class TokenPackController : BasicController
    {
        [Authorize]
        public ActionResult Buy(int id)
        {
            SessionInitialize();

            TokenPackCAD tokenPackCAD = new TokenPackCAD(session);
            TokenPackCEN tokenPackCEN = new TokenPackCEN(tokenPackCAD);

            TokenPackEN tokenPackEN = tokenPackCEN.ReadOID(id);
            TokenPackAssembler assembler = new TokenPackAssembler();
            TokenPackViewModel model = assembler.ConvertENToModelUI(tokenPackEN);

            SessionClose();

            return View(model);
        }

        // POST: TokenPack/Create
        [HttpPost]
        [Authorize]
        public ActionResult Buy(TokenPackViewModel model)
        {
            VirtualUserEN virtualUserEN = Session["User"] as VirtualUserEN;
            try
            {
                // TODO: Add insert logic here
                TokenPackCP tokenPackCP = new TokenPackCP();
                

                tokenPackCP.PurchaseTokenPack(model.Id, virtualUserEN.Id);

                virtualUserEN.Tokens += model.Tokens;
                TempData["OperationResult"] = new OperationResultViewModel(ModalMessageType.Success, "Compra realizada", 
                    "Tu compra de '" + model.Name + "' se ha realizado correctamente");
                return RedirectToAction("TokenPacks", "Shop");
            }
            catch
            {
                TempData["OperationResult"] = new OperationResultViewModel(ModalMessageType.Success, "Error",
                    "Se ha producido un error al intentar efectuar la compra.");
                return RedirectToAction("Details", "VirtualUser", new { id = virtualUserEN.Id });
            }
        }
    }
}

VirtualDeckWeb/Views/TokenPack/Buy.cshtml
@model VirtualDeckWeb.Models.TokenPackViewModel

@{
    ViewBag.Title = "Detalle Pack Tokens";
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12 ">
            <div class="centered-col-container">
                <div class="token-pack-container">
                    <div>
                        <h3>@Html.DisplayFor(modelItem => Model.Name)</h3>
                        <img src="~/Resources/token.png" alt="token">
                    </div>
                    <div style="margin: auto">
                        <h4>@Html.DisplayFor(modelItem => Model.Tokens) Tokens</h4>
                        <h4>@Html.DisplayFor(modelItem => Model.Price) €</h4>
                    </div>
                </div>
            </div>  
        </div>
        <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12">
            <div class="centered-col-container">
                @using (Html.BeginForm("Buy", "TokenPack", FormMethod.Post, new { @class = "default-form default-form-border", role = "form", style="padding-top: 0; width: 350px;" }))
                {
                    @Html.AntiForgeryToken()
                    <h3 class="section-title" style="font-weight: bold">Introduzca los datos bancarios</h3>
                                        
                    <div class="default-form-group">
                        @Html.LabelFor(m => m.AccountHolder)
                        <div class="text-box-container">
                            @Html.TextBoxFor(m => m.AccountHolder, new { @class = "text-box" })
                            <span class="text-box-outline"></span>
                        </div>
                        @Html.ValidationMessageFor(m => m.AccountHolder, "", new { @class = "error-message" })
                    </div>

                    <div class="default-form-group">
                        @Html.LabelFor(m => m.ExpiryDate)
                        <div class="text-box-container">
                            @Html.TextBoxFor(m => m.ExpiryDate, "{0:dd/MM/yyyy}", new { @class = "text-box" })
                            <span class="text-box-outline"></span>
                        </div>
                        @Html.ValidationMessageFor(m => m.ExpiryDate, "", new { @class = "error-message" })
                    </div>

                    <div class="default-form-group">
                        @Html.LabelFor(m => m.CardNumber)
                        <div class="text-box-container">
                            @Html.TextBoxFor(m => m.CardNumber, new { @class = "text-box" })
                            <span class="text-box-outline"></span>
                        </div>
                        @Html.ValidationMessageFor(m => m.CardNumber, "", new { @class = "error-message" })
                    </div>

                    <div class="default-form-group">
                        @Html.LabelFor(m => m.CVV)
                        <div class="text-box-container">
                            @Html.TextBoxFor(m => m.CVV, new { @class = "text-box" })
                            <span class="text-box-outline"></span>
                        </div>
                        @Html.ValidationMessageFor(m => m.CVV, "", new { @class = "error-message" })
                    </div>

                    @Html.HiddenFor(m => m.Id)
                    @Html.HiddenFor(m => m.Name)
                    @Html.HiddenFor(m => m.Tokens)

                    <div class="form-submit-group">
                        <input type="submit" value="Realizar compra" class="action-button" />
                    </div>
                }
            </div>
        </div>
    </div>


    <!--
        @using (Html.BeginForm("Buy", "TokenPack", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
        {
            @Html.AntiForgeryToken()
            <h4>Introduzca los datos bancarios</h4>
            <hr />
            @Html.ValidationSummary("", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(m => m.AccountHolder, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.AccountHolder, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.AccountHolder, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.ExpiryDate, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.ExpiryDate, "{0:dd/MM/yyyy}", new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.ExpiryDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.CardNumber, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.CardNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.CardNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.CVV, new { @class = "col-md-2 control-label" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.CVV, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.CVV, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.HiddenFor(m => m.Id)

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Realizar compra" class="action-button" />
                </div>
            </div>
        }-->
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }