VirtualDeckWeb/Models/PackViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using VirtualDeckGenNHibernate.Enumerated.VirtualDeck;

namespace VirtualDeckWeb.Models
{
    public class PackViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }


        public string Description { get; set; }

        public double Price { get; set; }

        public string Img { get; set; }

        public DateTime RegistryDate { get; set; }

        public int MaxNumCards { get; set; }


        public int MinNumCards { get; set; }

        public RarityEnum Rarity { get; set; }
        public CardTypeEnum CardTypes { get; set; }
        public RarityEnum CardRarities { get; set; }
    }
}

VirtualDeckWeb/Controllers/PackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VirtualDeckGenNHibernate.CAD.VirtualDeck;
using VirtualDeckGenNHibernate.CEN.VirtualDeck;
using VirtualDeckGenNHibernate.EN.VirtualDeck;
using VirtualDeckGenNHibernate.CP.VirtualDeck;
using VirtualDeckWeb.Assemblers;
using VirtualDeckWeb.Models;

namespace VirtualDeckWeb.Controllers
{
    public class PackController : BasicController
    {
        // GET: Pack
        public ActionResult Index(String search)
        {
            SessionInitialize();

            PackCAD packcad = new PackCAD(session);
            PackCEN packcen = new PackCEN(packcad);
            IList<PackEN> packs = null;
            
            if(search != null && search != "")
                packs = packcen.PacksByNameOrDescription(search);
            else
                packs = packcen.ReadAll(0, -1);

            IEnumerable<PackViewModel> listaPacks = new PackAssembler().ConvertListENToModel(packs).ToList();

            SessionClose();

            return View(listaPacks);
        }

        // GET: Pack/Details/5
        public ActionResult Details(int id)
        {
            SessionInitialize();
            PackCAD packCAD = new PackCAD(session);
            PackCEN packCEN = new PackCEN(packCAD);
            PackEN packEN = packCEN.ReadOID(id);
            PackViewModel model = new PackAssembler().ConvertENToModelUI(packEN);
            SessionClose();
            return View(model);

            /*
            SessionInitialize();
            CardCAD cardCAD = new CardCAD(session);
            CardCEN cardCEN = new CardCEN(cardCAD);
            CardEN cardEN = cardCEN.ReadOID(id);

            //List<AttackMoveEN> list = cardEN.AttackMoves.ToList();
            //IEnumerable<AttackMoveViewModel> attackList = new AttackMoveAssembler().ConvertListENToModel(list).ToList();

            PackViewModel model = new PackAssembler().ConvertENToModelUI(packEN);

            //ViewData["Card"] = model;
            //ViewData["Attack"] = attackList;

            SessionClose();
            return View(model);
            */
        }

        // POST: Pack/Buy
        [HttpPost]
        public ActionResult Buy(FormCollection collection)
        {
            int packId = 0;
            try
            {
                //SessionInitialize();
                packId = Int32.Parse(collection.Get("packId"));
                // TODO: Add insert logic here
                int amount = Int32.Parse(collection.Get("amount"));

                UserPackCEN userPackCEN = new UserPackCEN();
                PackCEN packCEN = new PackCEN();
                PackEN pack = packCEN.ReadOID(packId);
                VirtualUserEN user = Session["User"] as VirtualUserEN;

                PackCP packCP = new PackCP();
                packCP.PurchaseUserPack(packId, user.Id, amount);
                user.Tokens -= pack.Price * amount;
                TempData["OperationResult"] = new OperationResultViewModel(ModalMessageType.Success, "Compra realizada",
                    "Tu compra de '" + pack.Name + "' se ha realizado correctamente");
                return RedirectToAction("Packs", "Shop");
            }
            catch
            {
                TempData["OperationResult"] = new OperationResultViewModel(ModalMessageType.Error, "Error",
                   "No tienes suficiente dinero");
                return RedirectToAction("Details", new { id = packId });
            }
        }


        /*public ActionResult Search(FormCollection collection)
        {
            SessionInitialize();
            Console.WriteLine("Entro");
            PackCAD packcad = new PackCAD(session);
            PackCEN packcen = new PackCEN(packcad);
            IList<PackEN> packs = packcen.PacksByNameOrDescription(collection["packNameOrDescription"]);
            IEnumerable<PackViewModel> listaPacks = new PackAssembler().ConvertListENToModel(packs).ToList();
            SessionClose();
            return View(listaPacks);
        }*/
    }
}

VirtualDeckWeb/Views/Pack/Details.cshtml
@model VirtualDeckWeb.Models.PackViewModel
@using VirtualDeckGenNHibernate.EN.VirtualDeck;
@using VirtualDeckGenNHibernate.Enumerated.VirtualDeck;
@using System.Collections.Generic;

@{
    ViewBag.Title = "Detalle Sobre";
}

@if (Session["user"] != null)
{
    VirtualUserEN en = Session["user"] as VirtualUserEN;

    int id = en.Id;

    <div class="detalleTokens">
        <p class="userInfoTokens tokensTienda"><strong>Tokens: </strong><span>@en.Tokens <img src="~/Resources/token.png" /></span></p>
    </div>

}

<div class="container superior">
    <div class="row">
        <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
            @Html.Partial("PackPartial", Model)

        </div>
        <div class="col-lg-8 col-md-8 col-sm-6 col-xs-12  details">
            @using (Html.BeginForm("Buy", "Pack", FormMethod.Post))
            {
                <h3>@Html.DisplayFor(model => model.Name)</h3>
                <p>@Html.DisplayFor(model => model.Description)</p>
                
                <div>
                    <label>Precio</label>
                    <p class="price">@Html.DisplayFor(model => model.Price)<img src="~/Resources/token.png" alt="Tokens" class="token"></p>
                </div>
                <div>
                    <label for="cantidad">Cantidad</label>
                    <input type="number" id="cantidad" name="amount" min="1" value="1" max="50" onchange="changeTokens(this);" />
                </div>
                <div>
                    <label>Precio total</label>
                    <p><span class="totalPrice">@Html.DisplayFor(model => model.Price)</span><span><img src="~/Resources/token.png" alt="Tokens" class="token"></span></p>
                </div>
                VirtualUserEN user = Session["User"] as VirtualUserEN;
                if (user != null)
                {
                    <input type="submit" value="Comprar" class="action-button" />
                }
                else
                {
                    @Html.ActionLink("Comprar", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "action-button" })
                }


                <input type="hidden" value="@Model.Id" name="packId">
            }
        </div>
    </div>
</div>


<div class="container">
    <h3 class="centrarH2"><strong>Características</strong></h3>
    <hr class="marginHR">
    <div class="description">
        <div>
            <label for="cantidad">Nombre:</label>
            <p>@Html.DisplayFor(model => model.Name)</p>
        </div>
        <div>
            <label for="cantidad">Descripción:</label>
            <p>@Html.DisplayFor(model => model.Description)</p>
        </div>
        <div>
            <label for="cantidad">Máximo de cartas:</label>
            <p>@Html.DisplayFor(model => model.MaxNumCards)</p>
        </div>
        <div>
            <label for="cantidad">Mínimo de cartas:</label>
            <p>@Html.DisplayFor(model => model.MinNumCards)</p>
        </div>
        @{
            Dictionary<CardTypeEnum, string> cardTypes = new Dictionary<CardTypeEnum, string>()
            {
                { CardTypeEnum.Bug, "Bicho" },
                { CardTypeEnum.Dragon, "Dragon" },
                { CardTypeEnum.Electric, "Electrico" },
                { CardTypeEnum.Fighting, "Lucha" },
                { CardTypeEnum.Fire, "Fuego" },
                { CardTypeEnum.Flying, "Volador" },
                { CardTypeEnum.Ghost, "Fantasma" },
                { CardTypeEnum.Grass, "Hierba" },
                { CardTypeEnum.Ground, "Tierra" },
                { CardTypeEnum.Ice, "Hielo" },
                { CardTypeEnum.Normal, "Normal" },
                { CardTypeEnum.Poison, "Veneno" },
                { CardTypeEnum.Psychic, "Psíquico" },
                { CardTypeEnum.Rock, "Roca" },
                { CardTypeEnum.Water, "Agua" }
            };

            List<string> packCardTypes = new List<string>();
            foreach (int type in Enum.GetValues(typeof(CardTypeEnum)))
            {
                CardTypeEnum currentType = (CardTypeEnum)type;
                if ((Model.CardTypes & currentType) != CardTypeEnum.None && cardTypes.ContainsKey(currentType))
                {
                    packCardTypes.Add(currentType.ToString() + ".png");
                }
            }

            Dictionary<RarityEnum, string> cardRarities = new Dictionary<RarityEnum, string>()
            {
                { RarityEnum.Basic, "Básica" },
                { RarityEnum.Common, "Común" },
                { RarityEnum.Uncommon, "Poco común" },
                { RarityEnum.Rare, "Rara" },
                { RarityEnum.Epic, "Épica" },
                { RarityEnum.Legendary, "Legendaria" },
                { RarityEnum.Mythical, "Mítica" }
            };

            List<string> packCardRarities = new List<string>();
            foreach (int type in Enum.GetValues(typeof(RarityEnum)))
            {
                RarityEnum currentType = (RarityEnum)type;
                if ((Model.CardRarities & currentType) != RarityEnum.None && cardRarities.ContainsKey(currentType))
                {
                    packCardRarities.Add(cardRarities[currentType]);
                }
            }
        }

        <div>
            <label for="cantidad">En este sobre pueden aparecer cartas de rareza: </label>
            <p>@String.Join(", ", packCardRarities.ToArray())</p>
        </div>

        <div>
            <label for="cantidad">En este sobre pueden aparecer cartas de tipo: </label>
            <div>
                @for (int i = 0; i < cardTypes.Count; ++i)
                {
                    <img src="~/Resources/IconTypes/@packCardTypes[i]" style="width: 2em;" />
                }
            </div>
        </div>
    </div>
</div>

<div class="container">
    @{
        Html.RenderAction("ListPartial", "Comment", new { productID = Model.Id });
    }
</div>


@Html.Partial("OperationResultPartial")